# -*- coding: utf-8 -*-

"""
paginationtester

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from paginationtester.api_helper import APIHelper


class Links(object):

    """Implementation of the 'Links' model.

    Attributes:
        first (str): The model property of type str.
        last (str): The model property of type str.
        prev (str): The model property of type str.
        next (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "first": 'first',
        "last": 'last',
        "prev": 'prev',
        "next": 'next'
    }

    _optionals = [
        'first',
        'last',
        'prev',
        'next',
    ]

    def __init__(self,
                 first=APIHelper.SKIP,
                 last=APIHelper.SKIP,
                 prev=APIHelper.SKIP,
                 next=APIHelper.SKIP):
        """Constructor for the Links class"""

        # Initialize members of the class
        if first is not APIHelper.SKIP:
            self.first = first 
        if last is not APIHelper.SKIP:
            self.last = last 
        if prev is not APIHelper.SKIP:
            self.prev = prev 
        if next is not APIHelper.SKIP:
            self.next = next 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        first = dictionary.get("first") if dictionary.get("first") else APIHelper.SKIP
        last = dictionary.get("last") if dictionary.get("last") else APIHelper.SKIP
        prev = dictionary.get("prev") if dictionary.get("prev") else APIHelper.SKIP
        next = dictionary.get("next") if dictionary.get("next") else APIHelper.SKIP
        # Return an object of this model
        return cls(first,
                   last,
                   prev,
                   next)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'first={(self.first if hasattr(self, "first") else None)!r}, '
                f'last={(self.last if hasattr(self, "last") else None)!r}, '
                f'prev={(self.prev if hasattr(self, "prev") else None)!r}, '
                f'next={(self.next if hasattr(self, "next") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'first={(self.first if hasattr(self, "first") else None)!s}, '
                f'last={(self.last if hasattr(self, "last") else None)!s}, '
                f'prev={(self.prev if hasattr(self, "prev") else None)!s}, '
                f'next={(self.next if hasattr(self, "next") else None)!s})')
