# -*- coding: utf-8 -*-

"""
paginationtester

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from paginationtester.api_helper import APIHelper


class Transaction(object):

    """Implementation of the 'Transaction' model.

    Attributes:
        id (str): The model property of type str.
        amount (float): The model property of type float.
        timestamp (datetime): The model property of type datetime.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "amount": 'amount',
        "timestamp": 'timestamp'
    }

    _optionals = [
        'id',
        'amount',
        'timestamp',
    ]

    def __init__(self,
                 id=APIHelper.SKIP,
                 amount=APIHelper.SKIP,
                 timestamp=APIHelper.SKIP):
        """Constructor for the Transaction class"""

        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id 
        if amount is not APIHelper.SKIP:
            self.amount = amount 
        if timestamp is not APIHelper.SKIP:
            self.timestamp = APIHelper.apply_datetime_converter(timestamp, APIHelper.RFC3339DateTime) if timestamp else None 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get("id") if dictionary.get("id") else APIHelper.SKIP
        amount = dictionary.get("amount") if dictionary.get("amount") else APIHelper.SKIP
        timestamp = APIHelper.RFC3339DateTime.from_value(dictionary.get("timestamp")).datetime if dictionary.get("timestamp") else APIHelper.SKIP
        # Return an object of this model
        return cls(id,
                   amount,
                   timestamp)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'id={(self.id if hasattr(self, "id") else None)!r}, '
                f'amount={(self.amount if hasattr(self, "amount") else None)!r}, '
                f'timestamp={(self.timestamp if hasattr(self, "timestamp") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'id={(self.id if hasattr(self, "id") else None)!s}, '
                f'amount={(self.amount if hasattr(self, "amount") else None)!s}, '
                f'timestamp={(self.timestamp if hasattr(self, "timestamp") else None)!s})')
